workflows:
  android-build:
    name: Vizo Plus Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Capacitor Android Setup
        script: |
          # Buat folder www jika belum ada
          mkdir -p www
          # Sinkronisasi konfigurasi
          npx cap sync
          # Tambah folder android secara paksa
          npx cap add android || echo "Android already exists"
          # Salin file Firebase ke lokasi yang benar
          mkdir -p android/app
          cp google-services.json android/app/ || echo "Warning: google-services.json not found"
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - mholis1991@gmail.com
