workflows:
  android-build:
    name: Vizo Plus Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Capacitor Android Setup
        script: |
          # Inisialisasi jika belum ada
          npx cap init VizoPlus com.vizo.app --web-dir www --confirm
          npx cap add android || echo "Android platform already exists"
          # Sinkronisasi file www ke dalam folder android
          npx cap copy android
          # Salin file firebase ke tempat yang benar
          cp google-services.json android/app/
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - GANTI_DENGAN_EMAIL_KAMU@gmail.com
